# Parameters for Hector SLAM - Mapping package

# For a full documentation of the parameters used by this package, please check
# http://wiki.ros.org/hector_mapping

# Tf use
use_tf_scan_transformation: true
use_tf_pose_start_estimate: false

# Map size / start point
map_resolution: 0.050
map_start_x: 0.53
map_start_y: 0.46
map_multi_res_levels: 2

# Map update parameters
update_factor_free: 0.4
update_factor_occupied: 0.9
map_update_distance_thresh: 0.4
map_update_angle_thresh: 0.06
laser_z_min_value: -1.0
laser_z_max_value: 1.0

# Advertising config
advertise_map_service: true
