# Move Base Flex - Local Planner

controllers:
  - name: 'TebLocalPlannerROS'
    type: 'teb_local_planner/TebLocalPlannerROS'

# The rate in Hz at which to run the control loop and send velocity
# commands to the base.
controller_frequency: 5.0
# How long the controller will wait in seconds without receiving a
# valid control before space-clearing operations are performed.
controller_patience: 3.0
