# Move Base Flex - Global planner

planners:
  - name: 'GlobalPlanner'
    type: 'global_planner/GlobalPlanner'

# The rate in Hz at which to run the global planning loop. If the
# frequency is set to 0.0, the global planner will only run when a new
# goal is received or the local planner reports that its path is
# blocked.
planner_frequency: 1.0
# How long the planner will wait in seconds in an attempt to find a
# valid plan before space-clearing operations are performed.
planner_patience: 5.0

